image_width: 1280
image_height: 720
camera_name: "usb_2.0_camera:_hd_usb_camera"
camera_matrix:
  rows: 3
  cols: 3
  data: [407.43665,   0.     , 639.5    ,
           0.     , 407.43665, 359.5    ,
           0.     ,   0.     ,   1.     ]
distortion_model: equidistant
distortion_coefficients:
  rows: 1
  cols: 4
  data: [0.000000, 0.000000, 0.000000, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [407.43665,   0.     , 639.5    ,   0.     ,
           0.     , 407.43665, 359.5    ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]


# image_width: 1280
# image_height: 720
# camera_name: "usb_2.0_camera:_hd_usb_camera"
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [407.43665,   0.     , 639.5    ,
#            0.     , 407.43665, 359.5    ,
#            0.     ,   0.     ,   1.     ]
# distortion_model: equidistant
# distortion_coefficients:
#   rows: 1
#   cols: 4
#   data: [0.000000, 0.000000, 0.000000, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [407.43665,   0.     , 639.5    ,   0.     ,
#            0.     , 407.43665, 359.5    ,   0.     ,
#            0.     ,   0.     ,   1.     ,   0.     ]
