base_link:
  velodyne_rear_base_link:
    x: -0.267
    y: 0.0
    z: 0.262
    roll: 0.0
    pitch: 0.0
    yaw: 3.1415926535
  velodyne_front_base_link:
    x: 0.705
    y: 0.0
    z: 0.262
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_bottom_link:
    x: -0.08
    y: 0.0
    z: 0.222
    roll: 3.1415926535
    pitch: 0.0
    yaw: 0.0
