base_link:
  sensor_kit_base_link:
    x: 0.9
    y: 0.0
    z: 2.0
    roll: -0.001
    pitch: 0.015
    yaw: -0.0364
  velodyne_rear_base_link:
    x: -0.267
    y: 0.0
    z: 0.262
    roll: 0.0
    pitch: 0.0
    yaw: 3.1415926535
  velodyne_front_base_link:
    x: 0.705
    y: 0.0
    z: 0.262
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_bottom_link:
    x: -0.08
    y: 0.0
    z: 0.222
    roll: 3.1415926535
    pitch: 0.0
    yaw: 0.0
    sensor:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0
      pitch: 0.0
      yaw: 0.0


# base_link:
#   sensor_kit_base_link:
#     x: 0.9
#     y: 0.0
#     z: 2.0
#     roll: -0.001
#     pitch: 0.015
#     yaw: -0.0364
#   velodyne_rear_base_link:
#     # x: -0.358
#     # y: 0.0
#     # z: 1.631
#     # roll: -0.02
#     # pitch: 0.7281317
#     # yaw: 3.141592


#     x: 0.0
#     y: 0.3
#     z: 1.75

#     roll: -0.00
#     pitch: 0.0
#     yaw: -1.5707963267948966